# Generated by Django 5.1.2 on 2024-10-24 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        max_length=50, verbose_name="Место выполнения привычки"
                    ),
                ),
                (
                    "time",
                    models.TimeField(
                        max_length=25,
                        verbose_name="Время, когда надо выполнить привычку",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        max_length=100, verbose_name="Действие, которое надо выполнить"
                    ),
                ),
                (
                    "duration",
                    models.PositiveSmallIntegerField(
                        blank="True",
                        null="True",
                        verbose_name="Время на выполнение привычки",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank="True",
                        max_length=50,
                        null="True",
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "is_enjoyable",
                    models.BooleanField(
                        choices=[(True, "Приятная"), (False, "Полезная")],
                        default=True,
                        verbose_name="Приятная",
                    ),
                ),
                (
                    "is_daily",
                    models.BooleanField(
                        choices=[(True, "Ежедневная"), (False, "Еженедельная")],
                        default=True,
                        verbose_name="Периодичность",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        choices=[(True, "Публичная"), (False, "Личная")],
                        default=True,
                        verbose_name="Публичная",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
                (
                    "related",
                    models.ForeignKey(
                        blank="True",
                        null="True",
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="habits.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
