# Generated by Django 5.1.2 on 2024-10-29 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0004_alter_habit_is_enjoyable_alter_habit_is_public"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="frequency",
            field=models.PositiveSmallIntegerField(
                blank="True",
                default=7,
                null="True",
                verbose_name="Периодичность (сколько в неделю)",
            ),
        ),
    ]
