# Generated by Django 5.1.2 on 2024-10-30 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_alter_habit_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='frequency',
            field=models.PositiveSmallIntegerField(blank='True', default=7, null='True', verbose_name='Периодичность (раз в неделю)'),
        ),
    ]
